POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "super",
  "username": "jd123"
}



###
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Basic jd123 super

{
  "title": "Primeira task",
  "description": "Deve melhorar essa api",
  "priority": "Alta",
  "startAt": "2023-04-12T12:30:00",
  "endAt":"2023-05-12T12:30:00",
  "idUser" :"will-not-be-set"
}
